#ifndef SETTINGS_INCLUDED
#define SETTINGS_INCLUDED

// BEGIN Port Setttings
#define ROBOT_SERIAL_PORT_SPEED 9600
#define ROBOT_SERIAL_PORT_ADDRESS "/dev/ttyACM0"
#define ROBOT_SERIAL_PORT_HELLO_BYTE '+'
#define ROBOT_SERIAL_PORT_SESSION_TIMEOUT 30
// END Port Settings

// BEGIN Services
#define ROBOT_SERVICE_CAMERA 'C'
#define ROBOT_SERVICE_IMO 'I'
#define ROBOT_SERVICE_WHEEL_ANGLE 'A'
#define ROBOT_SERVICE_WHEEL_SPEED 'S'
#define ROBOT_SERVICE_WHEEL_ENCODER 'D'
#define ROBOT_SERVICE_IRSENSOR_SERVO 'I'
#define ROBOT_SERVICE_IRSENSOR_POLL 'J'
// END Services

// BEGIN Responses

// END Responses


#endif // SETTINGS_INCLUDED

