#ifndef SETTINGS_INCLUDED
#define SETTINGS_INCLUDED

#define ROBOT_SERIAL_PORT_SPEED 9600
#define ROBOT_SERIAL_PORT_ADDRESS "/dev/ttyACM0"
#define ROBOT_SERIAL_PORT_HELLO_BYTE '+'
#define ROBOT_SERIAL_PORT_SESSION_TIMEOUT 30

#endif // SETTINGS_INCLUDED

