#ifndef ARM_DRIVER_INCLUDED
#define ARM_DRIVER_INCLUDED

#define ARM_SERVOS 3
#define ARM_DELAYMS 150
#define ARM_SERVO_ID1 5
#define ARM_SERVO_ID2 6
#define ARM_SERVO_ID3 10

#endif // ARM_DRIVER_INCLUDED

