#ifndef SETTINGS_HEADER_INCLUDED
#define SETTINGS_HEADER_INCLUDED

#define PORT_SPEED 115200//9600
#define MAX_MESSAGE_SIZE 200
#define MSG_TERMINATOR ';'
#define MSG_START ':'

#endif // SETTINGS_HEADER_INCLUDED
